"""
Execution-validation orchestrator.

Takes the scripts generated by the BMAD loop for the grounded stories
(results/execution_validation/<model>/<framework>/TC_G*.json), writes each
final_script out as a real spec file, executes it headlessly against the
live application it was written for, and records genuine pass/fail/error
outcomes per story.

Usage (from execution_harness/):
  python run_execution.py                          # everything present
  python run_execution.py --model phi3 --framework cypress
"""
import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path

HARNESS_DIR = Path(__file__).parent
BASE_DIR    = HARNESS_DIR.parent
RESULTS_DIR = BASE_DIR / "results" / "execution_validation"
STORIES     = BASE_DIR / "data" / "execution_validation" / "grounded_stories.jsonl"
OUT_DIR     = RESULTS_DIR / "execution_outcomes"

CY_SPEC_DIR = HARNESS_DIR / "cypress" / "e2e"
PW_SPEC_DIR = HARNESS_DIR / "pw_specs"

SPEC_TIMEOUT_S = 240  # per-spec subprocess ceiling (live-site latency + retries)


def load_base_urls() -> dict:
    urls = {}
    with open(STORIES) as f:
        for line in f:
            r = json.loads(line)
            urls[r["id"]] = r["base_url"]
    return urls


def run_cypress(spec_path: Path, base_url: str) -> dict:
    """Run one Cypress spec; parse the mocha-json reporter from stdout."""
    proc = subprocess.run(
        ["npx", "cypress", "run", "--spec", str(spec_path),
         "--reporter", "json", "--quiet"],
        cwd=HARNESS_DIR, capture_output=True, text=True,
        timeout=SPEC_TIMEOUT_S,
        env={**__import__("os").environ, "CYPRESS_BASE_URL": base_url},
    )
    out = proc.stdout
    # The mocha json reporter emits a single {...} object; find its bounds.
    start, end = out.find("{"), out.rfind("}")
    if start == -1 or end == -1:
        return {"status": "load_error", "tests": 0, "passed": 0, "failed": 0,
                "detail": (proc.stderr or out)[-400:]}
    try:
        rep = json.loads(out[start:end + 1])
        stats = rep.get("stats", {})
        tests, passed = stats.get("tests", 0), stats.get("passes", 0)
        failed = stats.get("failures", 0)
        failures = [
            {"title": f.get("fullTitle", ""), "message": (f.get("err", {}).get("message") or "")[:300]}
            for f in rep.get("failures", [])
        ]
        if tests == 0:
            return {"status": "load_error", "tests": 0, "passed": 0,
                    "failed": 0, "detail": (proc.stderr or out)[-400:]}
        status = "passed" if failed == 0 else "failed"
        return {"status": status, "tests": tests, "passed": passed,
                "failed": failed, "failures": failures}
    except json.JSONDecodeError:
        return {"status": "load_error", "tests": 0, "passed": 0, "failed": 0,
                "detail": out[-400:]}


def run_playwright(spec_path: Path, base_url: str) -> dict:
    """Run one Playwright spec with the JSON reporter to a file."""
    report = HARNESS_DIR / "pw-report.json"
    if report.exists():
        report.unlink()
    env = {**__import__("os").environ,
           "PW_BASE_URL": base_url,
           "PLAYWRIGHT_JSON_OUTPUT_NAME": str(report)}
    proc = subprocess.run(
        ["npx", "playwright", "test", str(spec_path), "--reporter=json"],
        cwd=HARNESS_DIR, capture_output=True, text=True,
        timeout=SPEC_TIMEOUT_S, env=env,
    )
    if not report.exists():
        return {"status": "load_error", "tests": 0, "passed": 0, "failed": 0,
                "detail": (proc.stderr or proc.stdout)[-400:]}
    rep = json.loads(report.read_text())
    stats = rep.get("stats", {})
    passed = stats.get("expected", 0)
    failed = stats.get("unexpected", 0)
    tests = passed + failed + stats.get("skipped", 0) + stats.get("flaky", 0)
    failures = []
    for suite in rep.get("suites", []):
        for spec in suite.get("specs", []):
            for t in spec.get("tests", []):
                if t.get("status") not in ("expected", "flaky"):
                    msg = ""
                    results = t.get("results", [])
                    if results and results[0].get("error"):
                        msg = (results[0]["error"].get("message") or "")[:300]
                    failures.append({"title": spec.get("title", ""), "message": msg})
    # Compile/collection errors surface as zero tests plus top-level errors
    if tests == 0:
        detail = "; ".join(e.get("message", "")[:200] for e in rep.get("errors", [])) \
                 or (proc.stderr or proc.stdout)[-400:]
        return {"status": "load_error", "tests": 0, "passed": 0, "failed": 0,
                "detail": detail}
    status = "passed" if failed == 0 else "failed"
    return {"status": status, "tests": tests, "passed": passed,
            "failed": failed, "failures": failures}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", choices=["phi3", "gemma4"], default=None)
    ap.add_argument("--framework", choices=["cypress", "playwright"], default=None)
    args = ap.parse_args()

    base_urls = load_base_urls()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    models = [args.model] if args.model else ["phi3", "gemma4"]
    frameworks = [args.framework] if args.framework else ["cypress", "playwright"]

    for model in models:
        for framework in frameworks:
            gen_dir = RESULTS_DIR / model / framework
            records = sorted(gen_dir.glob("TC_G*.json"))
            if not records:
                print(f"[{model}/{framework}] no generated records yet — skipping")
                continue

            print(f"\n{'='*60}\n  Executing {len(records)} scripts: {model}/{framework}\n{'='*60}")
            outcomes = []
            for rec_path in records:
                rec = json.loads(rec_path.read_text())
                tc_id = rec["tc_id"]
                script = rec["final_script"]
                base_url = base_urls[tc_id]

                if framework == "cypress":
                    CY_SPEC_DIR.mkdir(parents=True, exist_ok=True)
                    for old in CY_SPEC_DIR.glob("*.cy.js"):
                        old.unlink()
                    spec = CY_SPEC_DIR / f"{tc_id}.cy.js"
                    spec.write_text(script)
                    try:
                        result = run_cypress(spec, base_url)
                    except subprocess.TimeoutExpired:
                        result = {"status": "timeout", "tests": 0, "passed": 0, "failed": 0}
                else:
                    PW_SPEC_DIR.mkdir(parents=True, exist_ok=True)
                    for old in PW_SPEC_DIR.glob("*.spec.*"):
                        old.unlink()
                    spec = PW_SPEC_DIR / f"{tc_id}.spec.js"
                    spec.write_text(script)
                    try:
                        result = run_playwright(spec, base_url)
                    except subprocess.TimeoutExpired:
                        result = {"status": "timeout", "tests": 0, "passed": 0, "failed": 0}

                result.update({"tc_id": tc_id, "model": model,
                               "framework": framework, "base_url": base_url,
                               "bmad_accepted": rec.get("accepted"),
                               "bmad_score": rec.get("best_score")})
                outcomes.append(result)
                print(f"  {tc_id}  {result['status']:<11} "
                      f"tests={result['tests']} passed={result['passed']} failed={result['failed']}")

            out_path = OUT_DIR / f"{model}_{framework}.json"
            out_path.write_text(json.dumps(outcomes, indent=2))

            n = len(outcomes)
            fully = sum(1 for o in outcomes if o["status"] == "passed")
            partial = sum(1 for o in outcomes if o["status"] == "failed" and o["passed"] > 0)
            load_err = sum(1 for o in outcomes if o["status"] in ("load_error", "timeout"))
            t_total = sum(o["tests"] for o in outcomes)
            t_pass = sum(o["passed"] for o in outcomes)
            print(f"\n  Summary {model}/{framework}: "
                  f"{fully}/{n} specs fully passing, {partial} partially passing, "
                  f"{load_err} load errors/timeouts; "
                  f"{t_pass}/{t_total} individual tests passing")
            print(f"  Saved: {out_path}")


if __name__ == "__main__":
    main()
